services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    command: [ "redis-server", "--requirepass", "myRedisPassword" ]
    ports:
      - "6379:6379"
    # Se quiser nomear explicitamente o contêiner (opcional):
    # container_name: my-redis

volumes:
  postgres-data:
